language: java
sudo: false
env:
  global:
  - PGPORT=5433
  - PGDATABASE=external_storage
  - PGUSER=postgres
  - PGPASSWORD=postgres
  - PGHOST=localhost
jobs:
  include:
    - jdk: oraclejdk10
      env: DATABASE_URL='jdbc:postgresql://localhost:5433/external_storage' DATABASE_USERNAME='postgres' DATABASE_PASSWORD='postgres'
      addons:
        postgresql: "10"
        apt:
          packages:
            - postgresql-10
            - postgresql-client-10
cache:
  directories:
    - "$HOME/.m2"
