language: java
sudo: false
jdk:
  - openjdk10
before_install:
 - sudo service mysql stop
 - sudo docker run -d --name mysqlserver -p 3306:3306 -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=external_storage mysql:8
env:
  matrix:
    - DATABASE_URL='jdbc:mysql://localhost/external_storage' DATABASE_USERNAME='root' DATABASE_PASSWORD='root'
service:
  - docker
cache:
  directories:
    - "$HOME/.m2"

