language: java
jdk:
  - openjdk10
before_install:
  - sudo service stop mariadb
  - sudo mysqld_safe --skip-grant-tables --skip-networking &
  - sudo mysql -u root -e 'FLUSH PRIVILEGES;'
  - ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root';
  - exit
  - sudo mysql -u root -e 'create database external_storage;'
  - sudo service mariadb restart
env:
  matrix:
    - DATABASE_URL='jdbc:mysql://127.0.0.1/external_storage' DATABASE_USERNAME='root' DATABASE_PASSWORD='root'
addons:
  mariadb: '10.3.9'
cache:
  directories:
    - "$HOME/.m2"
