language: java
jdk:
  - oraclejdk10
  - openjdk10
services:
  - mysql
before_install:
  - apt-get install -y mysql-server
  - sudo systemctl start mysql
  - mysql -e 'create database external_storage;'
env:
  matrix:
    - DATABASE_URL='jdbc:mysql://localhost/external_storage' DATABASE_USERNAME='root' DATABASE_PASSWORD=''
cache:
  directories:
    - "$HOME/.m2"
