language: java
sudo: false
env:
  global:
    - PGPORT=5433
jobs:
  include:
    - jdk: oraclejdk10
      env: DATABASE_URL='jdbc:postgresql://localhost:5433/external_storage' DATABASE_USERNAME='travis' DATABASE_PASSWORD='travis'
      before_script:
        - psql -c "CREATE DATABASE external_storage;" -U travis
        - psql -c "ALTER USER travis WITH PASSWORD 'travis';" -U travis
      addons:
        postgresql: 10
        apt:
          packages:
            - postgresql-10
            - postgresql-client-10
cache:
  directories:
    - "$HOME/.m2"
