language: java
sudo: false

jobs:
  include:
    - jdk: oraclejdk10
     env: DATABASE_URL='jdbc:mysql://localhost/external_storage' DATABASE_USERNAME='root' DATABASE_PASSWORD='Password45'
     script:
      - sudo docker run --name sqlserver -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=Password45' -e MSSQL_PID=Developer -p 1433:1433 -d microsoft/mssql-server-linux:2017-CU8
      - sudo docker exec -it sqlserver /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'Password45' -Q 'create database external_storage'
cache:
  directories:
    - "$HOME/.m2"
