language: java
jdk:
  - openjdk10
before_install:
  - sudo chown mysql /
  - wget -c https://dev.mysql.com/get/mysql-apt-config_0.8.10-1_all.deb
  - sudo dpkg -i mysql-apt-config_0.8.10-1_all.deb
  - sudo apt-get update
  - sudo apt-get install -y mysql-server
  - sudo usermod -d /var/lib/mysql/ mysql
  - sudo chown mysql -R /var/run/mysqld
  - sudo chown mysql -R /var/log/mysql
  - sudo chmod 777 /etc/mysql/conf.d/mysql.cnf
  - sudo echo 'socket=/run/mysqld/mysqld.sock' >> /etc/mysql/conf.d/mysql.cnf
  - sudo chmod 0444 /etc/mysql/conf.d/mysql.cnf
  - sudo usermod -d /var/lib/mysql/ mysql
  - sudo service mysql start
  - sudo mysql ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root';
  - sudo mysql -u root -e 'create database external_storage;'
  - sudo service mysql restart
env:
  matrix:
    - DATABASE_URL='jdbc:mysql://127.0.0.1/external_storage' DATABASE_USERNAME='root' DATABASE_PASSWORD='root'
cache:
  directories:
    - "$HOME/.m2"
