language: java
jdk:
  - openjdk10
before_install:
  - wget -c https://dev.mysql.com/get/mysql-apt-config_0.8.10-1_all.deb
  - sudo dpkg -i mysql-apt-config_0.8.10-1_all.deb
  - sudo apt-get update
  - sudo apt-get install -y mysql-server
  - sudo service mysql stop
  - sudo service mysql start
  - ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root';
  - sudo mysql -u root -e 'create database external_storage;'
env:
  matrix:
    - DATABASE_URL='jdbc:mysql://127.0.0.1/external_storage' DATABASE_USERNAME='root' DATABASE_PASSWORD='root'
cache:
  directories:
    - "$HOME/.m2"
