language: java
sudo: false

jobs:
  include:
    - jdk: oraclejdk10
      env: DATABASE_URL='jdbc:postgresql://localhost/external_storage' DATABASE_USERNAME='postgres' DATABASE_PASSWORD='postgres'
      before_script:
       - psql -c "CREATE DATABASE external_storage;" -U postgres
       - psql -c "ALTER USER postgres WITH PASSWORD 'postgres';" -U postgres
cache:
  directories:
    - "$HOME/.m2"
