language: java
jdk:
  - openjdk10
before_install:
  - wget -c https://dev.mysql.com/get/mysql-apt-config_0.8.10-1_all.deb
  - sudo dpkg -i mysql-apt-config_0.8.10-1_all.deb
  - sudo apt-get update
  - sudo apt-get install -y mysql-server
  - sudo service mysql stop
  - sudo service mysql start
  - sudo ln -s ~travis/.my.cnf /var/run/mysqld/mysqld.sock
  - mysql --protocol=tcp -e 'create database external_storage;'
env:
  matrix:
    - DATABASE_URL='jdbc:mysql://localhost/external_storage' DATABASE_USERNAME='root' DATABASE_PASSWORD=''
cache:
  directories:
    - "$HOME/.m2"
