language: java
sudo: false
env:
  global:
    - PGPORT=5433
jobs:
  include:
    - jdk: oraclejdk10
      env: DATABASE_URL='jdbc:postgresql://localhost:5433/external_storage' DATABASE_USERNAME='postgres' DATABASE_PASSWORD='postgres'
      before_script:
        - sudo su - postgres -c "psql --echo-all -U postgres -d postgres --command \"create database external_storage;\""
        - sudo su - postgres -c "psql --echo-all -U postgres -d postgres --command \"alter user postgres with password 'postgres';\""

      addons:
        postgresql: 10
        apt:
          packages:
            - postgresql-10
            - postgresql-client-10
cache:
  directories:
    - "$HOME/.m2"